### ISSUE TITLE
Typos in install.sh

### ISSUE THREAD

**Issue by Zedjones** [mariosemes/PornHub-downloader#1]
There are typos [here](https://github.com/mariosemes/PornHub-downloader/blob/70078e554ab6bf8997cfdcf747299540e5de9d05/install.sh#L7) and [here](https://github.com/mariosemes/PornHub-downloader/blob/70078e554ab6bf8997cfdcf747299540e5de9d05/install.sh#L13) in `install.sh`. 

I believe the commands should be `echo` instead of `ecto` :)

**Comment by mariosemes** [comment]
Thank you! Removed those lines.
